apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hs1xx-exporter.fullname" . }}
  labels:
{{ include "hs1xx-exporter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hs1xx-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hs1xx-exporter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hs1xx-exporter-configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "hs1xx-exporter.serviceAccountName" . }}
      restartPolicy: Always
      containers:
        # hs1xx-exporter container
        - name: hs1xx-exporter
          {{- $repo := required "image.repository is required" .Values.image.repository }}
          {{- $tag := required "image.tag is required" .Values.image.tag }}
          image: "{{ $repo }}:{{ $tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "--config-path"
          - "/app/config"
          {{- if .Values.debug }}
          - "--debug"
          {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.config.metricsPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: hs1xx-exporter-config
            mountPath: /app/config
      volumes:
      - name: hs1xx-exporter-config
        configMap:
          name: {{ .Release.Name }}-hs1xx-exporter-config
      {{- if .Values.extraVolumes  }}{{ toYaml .Values.extraVolumes | trim | nindent 6 }}{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
