{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "hs1xx-exporter.name" . }}
    chart: {{ template "hs1xx-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "hs1xx-exporter.serviceAccountName" . }}
{{- end -}}
